### ISSUE TITLE
Migrate to cedar-14

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/carnival#123]
We'd ultimately like to share build artifacts between Travis and Heroku using Halcyon  (see #121). This requires both environments be the same platform. It's also generally good to have CI build on as production-like as possible a platform anyway. Upgrading to cedar-14 would get us in line with what Travis is currently running our builds on and the migration looks very easy.

https://devcenter.heroku.com/articles/cedar-14-migration

- [x] migrate carnival-staging
- [x] migrate carnival-production

**Comment by pbrisbin** [comment]
Nevermind? It looks like Travis actually uses 12.04. Since cedar (current) is 10.04 and cedar-14 is 14.04, we might not get any benefit until moving to cedar-14 *and* Travis upgrades to 14.04.

**Comment by jferris** [comment]
It might be worth doing the update anyway, since it should be relatively painless, and we'd get updated versions of a number of system packages.

**Comment by pbrisbin** [comment]
Running [these steps](https://devcenter.heroku.com/articles/cedar-14-migration#upgrading-the-production-app-to-cedar-14) for staging right now.

**Comment by pbrisbin** [comment]
This is done.

I'm not 100% sure that production is migrated because the process is to set the new stack then perform a deploy. Since we deploy to production via copying the slug from staging, I don't know if that's the same thing. Either way, I'm going to close this issue.
