### ISSUE TITLE
Working demo page

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/carnival#159]
#152 adds such a page, but Carnival does not work as-is there. The elements are positioned incorrectly.

We need to change how things are done in either JS or CSS (or both) so that elements are positioned correctly in this simple layout (`article > p, article > pre`) without breaking the install on robots.thoughtbot.com (and ideally without adding a slew of site-specific options).

Once working, add a link to it on the Homepage.

**Comment by pbrisbin** [comment]
Maybe this page could double as the general marketing page?

**Comment by jferris** [comment]
I like the idea of using the marketing page as the demo page - just let people comment on the public pages of the site.

I'm guessing we'll have to monitor/prune the comments occasionally.

**Comment by pbrisbin** [comment]
Closing.

#163 fixes the bugs and #167 captures the need to "demo" by having comments on Carnival itself.
