### ISSUE TITLE
Initial Design Work

### ISSUE THREAD

**Issue by smharley** [thoughtbot/carnival#162]
Some initial mid-fidelity mockups
![landing - home](https://cloud.githubusercontent.com/assets/867169/6626959/e08b0c80-c8b7-11e4-9926-e3685b991b5e.png)
```





```
![site index - first site](https://cloud.githubusercontent.com/assets/867169/6626960/e28d4386-c8b7-11e4-81a0-ff10fdab55e4.png)
```





```
![add new site](https://cloud.githubusercontent.com/assets/867169/6626961/e47419b8-c8b7-11e4-9bf4-2d3c98c0c418.png)
```





```
![site index - with sites](https://cloud.githubusercontent.com/assets/867169/6626964/e947b4d6-c8b7-11e4-845c-afe5838a1068.png)
```





```
![edit site](https://cloud.githubusercontent.com/assets/867169/6626965/ec6fb546-c8b7-11e4-9312-469cbd4fd026.png)

**Comment by jferris** [comment]
Nice! I like the logo.

This is pretty straightforward, and I think it's just what we need.

A few notes:

* We removed most of the site fields. I think it's just "name," "url," and "language" now.
* Pat had the idea of allowing comments on the Carnival site itself, so the site also serves as the demo. Not sure if there's a way to work this into the design, but I liked the idea.
* I'm guessing most users will have exactly one site, so we may want to optimize for that. Might not be worth doing any changes for MVP, but I think it will make the experience slicker for most users.

**Comment by pbrisbin** [comment]
Yeah, I think this looks great!

My own thoughts:

- Keeping the new-site and site-index on the same page is convenient technically. Maybe now that there are fewer fields, we can keep that aspect?
- For the demo, we just need a copy-heavy page. So if Tour or Docs shapes up that way, we could ditch Demo and just self-install on that page

**Comment by smharley** [comment]
@pbrisbin what do you think about using a modal for the new site?

re: Demo, that sounds good! those links are mostly placeholder to get a sense of what the nav could be

**Comment by smharley** [comment]
I also assumed 1 site, but it was kind of a guess more than anything. I'll keep that in mind

**Comment by pbrisbin** [comment]
> what do you think about using a modal for the new site?

No problem with me. Is there any down-side?

**Comment by smharley** [comment]
not that i can think of. it would keep them on the same page, but without any clutter. downsides might come up if there end up being a lot of fields (not great for modals)

**Comment by pbrisbin** [comment]
Cool, I don't envision a lot of fields any time soon -- we're at 3 now.

**Comment by pbrisbin** [comment]
I've created separate Issues for each page that still requires styling (i.e. it still uses bootstrap). Free free to move the mocks to the appropriate issue or just use the back-reference to see them from there.

#220 #222 #223 #224 #225

**Comment by smharley** [comment]
:+1: sounds good, i'll be working on this tomorrow!
