### ISSUE TITLE
Non thoughtbot.com sub-domain URL

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/carnival#168]
- [x] register carnivalapp.io
- [x] point carnivalapp.io at heroku
- [x] add carnivapp.io domain to carnival-production
- [x] point carnival.thoughbot.com to a different *.thoughtbot.com herokussl endpoint
- [x] apply for carnivalapp.io SSL
- [x] set up carnivalapp.io herokussl endpoint
- [x] create new OAuth app on GitHub for new host
- [x] update `APPROOT` on carnival-production
- [x] update `CARNIVAL_HOST` on robots blog
- [ ] remove carnival.thoughtbot.com

**Comment by pbrisbin** [comment]
The obvious carnival.com/net/org/io are taken.

We could:

- Find a more exotic TLD
- Experiment with prefix/suffix: gocarnival.com, trycarnival.io, etc
- carniv.al seems to be available

I kind of like carniv.al, but I have this feeling it's a bad idea.

**Comment by pbrisbin** [comment]
- comments.hosting (looks available, might be too clever/confusing)
- carnivalcomments.com (available, won't work for twitter)
- carnivalapp.io (.com not available)

**Comment by gfontenot** [comment]
I vote for `carnivalapp.io`

**Comment by pbrisbin** [comment]
I agree. I'm going to move forward with that, unless there are objections.

/cc @jferris @cpytel @mjankowski @croaky

**Comment by croaky** [comment]
+1 `carnivalapp.io`

**Comment by pbrisbin** [comment]
carnivalapp.io purchased. Wildcard SSL application submitted, awaiting email..

**Comment by pbrisbin** [comment]
I'd prefer to update the host on the current OAuth application (if that's possible) so that users won't have to re-authorize. Will have to coordinate that and update `APPROOT` at the same time.

ping @jferris

**Comment by pbrisbin** [comment]
This is all set. I'm going to leave carnival.thoughtbot.com around for a bit just in case, but I purged the blog so nothing should be accessing it via that URL anymore.
