### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/carnival#174]
Just adding/un-commenting our code in settings.yml should do it. Actually setting up the site in GA would be the real work here.

**Comment by pbrisbin** [comment]
It looks like I can access GA through my tbot account, but not add a property. Can someone add carnivalapp.io, or give me permissions / tips to do so?

/cc @croaky

**Comment by croaky** [comment]
Sorry about that. Just made you an admin on the account but also created the property. You should be able to access it [here](https://www.google.com/analytics/web/?hl=en#report/visitors-overview/a1485842w95443472p99514181/).

Possible to use Segment from the app itself? I just created a project and hooked Google Analytics into it. [Setup page is here](https://segment.com/thoughtbot/carnival/setup). Will come in handy if and when we add Intercom and Mixpanel.

**Comment by pbrisbin** [comment]
Hey, I joined Segment and can see the carnival project, but I get a 401 on the setup page.

**Comment by croaky** [comment]
Sorry about that. Just made you an account owner on the organization. Do you have access now?

**Comment by pbrisbin** [comment]
I do, thanks!
