### ISSUE TITLE
Footer stops short on large monitors

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/carnival#193]
![carnival](https://cloud.githubusercontent.com/assets/50812/6740704/a1f6812e-ce58-11e4-8baa-6f2a226a090c.png)

The grey should extend all the way down, or the footer should stick at the bottom.

I'm told this is a case for flex box, but I couldn't get it working.

**Comment by pbrisbin** [comment]
Ping @smharley

**Comment by smharley** [comment]
The easiest way to solve this might be to change the html background color to the footer's gray, and make the body background color white? Something like that might work, but I'll figure out a permanent solution for this
