### ISSUE TITLE
Other authentication methods

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/carnival#196]
- [x] http://hackage.haskell.org/package/yesod-auth-1.4.4/docs/Yesod-Auth-GoogleEmail2.html
- [x] <del>https://hackage.haskell.org/package/yesod-auth-fb</del>
- [ ] Twitter (we'll write this ourselves in yesod-auth-oauth2)

**Comment by pbrisbin** [comment]
Adding Twitter to yesod-auth-oauth2: https://github.com/thoughtbot/yesod-auth-oauth2/pull/27

**Comment by pbrisbin** [comment]
Adding Google to carnival: https://github.com/thoughtbot/carnival/pull/212

**Comment by pbrisbin** [comment]
I'm going to consider this done for now. We won't be adding Twitter since it doesn't provide an Email. If folks feels strongly about providing FB, we can add a new issue for it.

**Comment by jferris** [comment]
It's too bad Twitter is such a pain. I feel like that's the most likely one people will use. Is there a way to get people to "finalize" OAuth2 logins, so that they enter an email after authenticating with Twitter?

Or, could we make `email` nullable? Is that a bad path to go down?

**Comment by pbrisbin** [comment]
We could probably add a custom screen to get an email from the user as part of on-boarding. I'm not sure what this'd look like or how difficult it'd be. I'd definitely prefer not to make `userEmail` a `Maybe`, but it's not the end of the world if the other options are too complicated. As of now, that would really just mean handling gravatars and notifications differently.
