### ISSUE TITLE
Style login page

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/carnival#220]

**Comment by smharley** [comment]
Does this page exist yet? If so, how do I get to it?

**Comment by pbrisbin** [comment]
Sorry, it's at `/auth/login`. All of our Sign In links still go direct to GitHub. Typing it directly or logging out seems to be the only way to get to it.

**Comment by smharley** [comment]
@pbrisbin should I change the sign in links to go to this page in my styling PR?

**Comment by pbrisbin** [comment]
Yeah, I think that's OK.

**Comment by smharley** [comment]
Fixed with #230
