### ISSUE TITLE
Follow conventions in JavaScript casing

### ISSUE THREAD

**Issue by jferris** [thoughtbot/carnival#247]
We're currently using underscored attributes (`article_author`), but it's more common in JavaScript to use camel case (`articleAuthor`).

We could look for both, but suggest camel case in the documentation.

**Comment by pbrisbin** [comment]
Is this just for passing options into `Carnival.init`, or also the API requests/resposes?

**Comment by jferris** [comment]
I think the things we intentionally expose to the user (`Carnival.init`) are most important.
