### ISSUE TITLE
Delete my stupid comment from the carnivalapp.io page

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/carnival#251]
I left a comment on the homepage of https://carnivalapp.io/ thinking it would be ephemeral and wouldn't persist after a reload.

I was wrong. My apologies.

**Comment by pbrisbin** [comment]
No worries! We expect to prune the demo comments from time to time, I can explicitly remove yours now if you like.

**Comment by geoffharcourt** [comment]
It looks like I wasn't the only one with a dumb idea, given the notifications that have started coming through. If you're going to regularly prune, no need to jump on just for me. I only didn't want my comment to live on forever. Thanks.
