### ISSUE TITLE
When comments run longer than the article, they bleed into footer

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/carnival#257]
![shot](https://cloud.githubusercontent.com/assets/50812/7206813/173484ac-e503-11e4-8e9c-db2d201b583c.png)

**Comment by gabebw** [comment]
`overflow: scroll`?

**Comment by pbrisbin** [comment]
It's a bit more complicated than that. These threads are contained in a `.carnival` div of no size and absolutely positioned to line up with the paragraphs. I think we would need to get that div to be the same height as the article, before we can think about how to position/constraint the threads within it.

**Comment by smharley** [comment]
`max-height` might also be a band-aid

**Comment by jferris** [comment]
The proposed `max-height` band-aid has been deployed, but it would be nice to come up with a more robust fix.

**Comment by pbrisbin** [comment]
Wild idea:

- Let `d` be the distance from the top of the thread from the top of the article
- Let `h` be the height of the article element
- In JS, set a `max-height` of `h - d` for each thread element
- Profit?
