### ISSUE TITLE
Please add type="text/javascript" to the script tags

### ISSUE THREAD

**Issue by jmn** [thoughtbot/carnival#262]
To fix (X)HTML validation errors.

**Comment by pbrisbin** [comment]
> `type="text/javascript"`
>
> This attribute is optional. Since Netscape 2, the default programming language in all browsers has been JavaScript. In XHTML, this attribute is required and unnecessary. In HTML, it is better to leave it out. The browser knows what to do.

[Source](http://javascript.crockford.com/script.html)

I tend to agree, and if we plan to support only HTML (not XHTML), I don't want to add that attribute. That said, this is a rather minor thing to do even if we don't fully support XHTML. I'll give it some thought.

Thanks!

**Comment by sarciszewski** [comment]
The correct MIME Type is `application/javascript`, which is the default.

**Comment by jferris** [comment]
Some versions of Internet Explorer [fail if you specify `application/javascript`](http://stackoverflow.com/questions/1288263/why-doesnt-ie8-recognize-type-application-javascript-in-a-script-tag).
