### ISSUE TITLE
Make it possible to delete comments

### ISSUE THREAD

**Issue by enaeher** [thoughtbot/carnival#264]
Ideally, both the site owner and the comment author should have the ability to delete a comment.

**Comment by dasilvacontin** [comment]
+1. You currently cannot delete 'test' comments, moderate, edit your typos, etc.

**Comment by anhari** [comment]
Anyone working on this currently?

**Comment by dasilvacontin** [comment]
@anhari I don't think so – project looks inactive / unmaintained.

**Comment by cpytel** [comment]
Carnival continues to work well for us on Giant Robots, we don't often find the need to delete or edit comments often at all, and in the rare case when we do we use the database to do so.

So we haven't felt the need to add this feature, and therefore haven't. 

If someone were to submit a PR with the feature we would certainly review and merge it.
