### ISSUE TITLE
HTML is unescaped

### ISSUE THREAD

**Issue by calebthompson** [thoughtbot/carnival#266]
![](http://caleb.click/ao0s/Image%202015-04-28%20at%201.14.43%20PM.png)

**Comment by jferris** [comment]
The comments are markdown, and a subset of HTML is allowed. This is normal in markdown parsers; for example, GitHub comments allow some HTML, and putting unescaped `<li>` tags in a GitHub comment gets you a list item.

You can see more details on the whitelist being used here: https://github.com/yesodweb/haskell-xss-sanitize

It's possible that markdown isn't the best format for our comments, but it seemed good to start with.

**Comment by calebthompson** [comment]
> The comments are markdown, and a subset of HTML is allowed. This is normal in markdown parsers; for example, GitHub comments allow some HTML, and putting unescaped <li> tags in a GitHub comment gets you a list item.

Yup, seems right.



> It's possible that markdown isn't the best format for our comments, but it seemed good to start with.

I'd have to see more use cases, but I don't think there's much value in markdown. Maybe a super-subset of markdown that allows for `_` => `<em>`, `*` => `<strong>`, and autolinks (which we don't have). Just a thought.
