### ISSUE TITLE
Unsubscribe may be broken

### ISSUE THREAD

**Issue by calebthompson** [thoughtbot/carnival#267]
> I unsubscribed from this thread and also removed the app from GitHub, but am still receiving updates.

**Comment by pbrisbin** [comment]
Do you have a username, site, article, or thread?

**Comment by calebthompson** [comment]
Here's the HTML, from the carnivalapp.io landing page:

```
<li id="comment-453" class="carnival-comment"><div class="carnival-author"><img src="https://www.gravatar.com/avatar/5d0b9f89c8dae06a874391a0822ffa86"><span>Paul Anthony Webb</span></div><div class="carnival-body"><p>I unsubscribed from this thread and also removed the app from GitHub, but am still receiving updates.</p></div></li>
```

**Comment by jferris** [comment]
I tried to reproduce this by subscribing/unsubscribing myself, but I stopped receiving emails after unsubscribing.

**Comment by calebthompson** [comment]
Sounds like it's been fixed or was a fluke then.

**Comment by jferris** [comment]
I wonder if maybe he subscribed to multiple threads and thought he was unsubscribing from every thread at once?

**Comment by pbrisbin** [comment]
I don't have access to the heroku app(s) anymore. But what I would do is find the user by name, then look at subscription by user id for records with active = true.
